# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Event

# Model Form Field configuration
form: $/scottjohnstone/ajaxpaginatedevents/models/event/fields.yaml

# Model Class name
modelClass: ScottJohnstone\AjaxPaginatedEvents\Models\Event

# Default redirect location
defaultRedirect: scottjohnstone/ajaxpaginatedevents/events

# Create page
create:
    title: Create Event
    redirect: scottjohnstone/ajaxpaginatedevents/events/update/:id
    redirectClose: scottjohnstone/ajaxpaginatedevents/events

# Update page
update:
    title: Edit Event
    redirect: scottjohnstone/ajaxpaginatedevents/events
    redirectClose: scottjohnstone/ajaxpaginatedevents/events

# Preview page
preview:
    title: Preview Event